CREATE DATABASE `spring-mvc-shop` DEFAULT CHARACTER
SET utf8 COLLATE utf8_general_ci;

USE `spring-mvc-shop`;

CREATE TABLE album (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
`name` VARCHAR ( 25 ) NOT NULL,
company VARCHAR ( 50 ) NULL,
image VARCHAR ( 50 ) NULL,
publishDate DATE NULL,
area VARCHAR ( 50 ) NULL,
description VARCHAR ( 50 ) NULL,
playCount INT NULL,
isValid TINYINT NULL,
version VARCHAR ( 10 ) NULL
) ENGINE = INNODB DEFAULT CHARSET = utf8;

CREATE TABLE course_info ( id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, `cname` VARCHAR ( 25 ) NOT NULL, caddress VARCHAR ( 50 ) NULL ) ENGINE = INNODB DEFAULT CHARSET = utf8;
CREATE TABLE user_info ( id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, uname VARCHAR ( 25 ) NOT NULL, unumber INT NULL ) ENGINE = INNODB DEFAULT CHARSET = utf8;
CREATE TABLE course_user_info(id INT NOT NULL, uid INT NOT NULL, cid INT NOT NULL)ENGINE = INNODB DEFAULT CHARSET = utf8;